config/routes.rb
Rails.application.routes.draw do

  root 'customers#new'
  resources :restaurants, only: [:index, :show] do
    resources :reservations, only: [:show, :create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :customers, only: [:new, :create, :show]

  get 'profile' => 'customers#show' # so my profile path shows up as profile and not reservation/show

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_secure_password

	validates :first_name, :last_name, :email, presence: true
	
	has_many :reservations
	has_many :restaurants, through: :reservations
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	
	belongs_to :customer
	belongs_to :restaurant

	validate :availability


	private
  def availability
    unless restaurant.available?(party_size, reservation_time)
      errors.add(:base, "Restaurant is full")
    end
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  has_many :reservations
  has_many :customers, through: :reservations

	def available?(party_size, start_time)
		reserved = reservations.where(:reservation_time => start_time).sum(:party_size)
		party_size <= (capacity - reserved)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


	def current_customer
		@current_customer ||= Customer.find(session[:customer_id]) if session[:customer_id]
	end
  
  helper_method :current_customer


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save 
      flash[:notice] = "Signed up"
      session[:customer_id] = @customer.id
      redirect_to restaurants_url
    else
      flash.now[:alert] = "oh, something bad happened."
      render "new"
    end
  end

  def show
  end

private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	# before_filter :ensure_logged_in


  def show
  	if current_customer
      @reservation = Reservation.find(params[:id])
    else
      redirect_to root_path 
    end
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
  	@reservation = @restaurant.reservations.build(reservation_params)
  	@reservation.customer = current_customer
  	if @reservation.save                
  		redirect_to customer_path(current_customer)  #need to create a confirmation page and path or we just redirect to restaurant list and write a notice that the restervation has been saved
  	else
  		render "restaurants/show"
  	end
  end

  def destroy
  	@reservation = current_customer.reservations.find(params[:id])
  	@reservation.destroy
    redirect_to customer_path(current_customer)
  end

  private
  def reservation_params
  	params.require(:reservation).permit(:reservation_time, :restaurant_id, :customer_id, :party_size)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  	@restaurants = Restaurant.all
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
    @reservation = Reservation.new
  end

  private
  def restaurant_params
  	params.require(:restaurant).permit(:name, :phone_number, :address, :capacity)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create #capturing the password and matching it to the user.
    # binding.pry
  	customer = Customer.find_by(email: params[:email])
  	if customer && customer.authenticate(params[:password])
      session[:customer_id] = customer.id
      redirect_to restaurants_url, notice: "Logged in!"
    else
      flash[:notice] = "Wrong password or user doesn't exist!"
      render "new"
    end
  end

  def destroy
  	session[:customer_id] = nil
  	redirect_to new_session_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/customers/new.html.erb
<div class="jumbotron">

<h1>Welcome to Open Sesame!</h1>


<%= form_for @customer do |f| %>
  <% if @customer.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @customer.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>


<br>
<br>

<h2>Log in</h2>
<%= form_tag sessions_path do %>
  <div class="field">
    <%= label_tag :email %><br/>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="field">
    <%= label_tag :password %><br/>
    <%= password_field_tag :password %>
  </div>
  <div class="actions"><%= submit_tag "Log in" %></div>
<% end %>
</div>

app/views/customers/show.html.erb
<h1>My Profile</h1>


<h2>These are your existing reservations:</h2>


<% current_customer.reservations.each do |reservation| %>
	<p>
		You have a reservation at <%= reservation.restaurant.name %>, 
		for <%= reservation.party_size %> people, 
		at <%= reservation.reservation_time.strftime("%l:%M %p") %> 
		on <%= reservation.reservation_time.strftime("%A, %B %d") %>. 

		<%= link_to "Cancel Reservation", restaurant_reservation_path(reservation.restaurant, reservation), :method => :delete %>
  	</p>


<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <img src="...">
      </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= restaurants_path %>">Open Sesame</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
      </ul> -->
      <!-- <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if current_customer %>
          <li><%= link_to "Log out", session_path("current"), :method => :delete %><li>
          <li><%= link_to "My Profile", profile_path %></li>
        <% else %>
          <li><%= link_to "Log in", new_session_path %></li>
          <li><%= link_to "Sign up", new_customer_path %></li>
          <%= form_tag sessions_path do %>
            <div class="field">
              <%= label_tag :email %>
              <%= text_field_tag :email, params[:email] %>
            </div>
            <div class="field">
              <%= label_tag :password %>
              <%= password_field_tag :password %>
            </div>
            <div class="actions"><%= submit_tag "Log in" %></div>
          <% end %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpenSesame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:alert] %>
		<p id="alert"><%= flash[:alert] %></p>
	<% end %>

<%= yield %>

</body>
</html>

app/views/reservations/new.html.erb
<%= form_for @reservation do |f| %>
	<div class="field">
		<%= f.label :reservation_time %><br/>
		<%= f.datetime_field :reservation_time %>
	</div>
	<div class="field">
		<%= f.label :party_size %><br/>
		<%= f.number_field :party_size %>
	</div>
	<div class="action">
		<%= f.submit %>
	</div>
<% end %>

app/views/reservations/show.html.erb
<h1>OpenSesame</h1>

<p class="userinfo">
        Signed in as <%= current_customer.first_name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
     
</p>

<h2><%= "Congratulations #{current_customer.first_name}!" %></h2>

<h3><%= "Your reservation has been booked at #{restaurant.name} for #{reservation.reservation_time}!" %> </h3>

app/views/restaurants/_form.html.erb
<% link_to 'My Profile', customer_path %><br/>
<% link_to 'Logout', session_path %>

app/views/restaurants/index.html.erb
<h1>OpenSesame</h1>
<h2>Book a Reservation!</h2>

<p class="userinfo">
      <% if current_customer %>
        Signed in as <%= current_customer.first_name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <% redirect_to root.path %>
      <% end %>
</p>



<% @restaurants.each do |restaurant| %>
	<p>
    <strong> <%= restaurant.name %> </strong>
    <%= link_to "Reserve now", restaurant_path(restaurant) %> 
  </p>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2>Make a Reservation:</h2>
<%= form_for [@restaurant, @reservation] do |f| %>
  <% if @reservation.errors.any? %>
    <div class="error_messages">
    Sorry! Really sorry.
        <% for message in @reservation.errors.full_messages %>
          <h2><%= message %></h2>
        <% end %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :reservation_time %><br/>
    <%= f.datetime_select :reservation_time %>
  </div>
  <div class="field">
    <%= f.label :party_size %><br/>
    <%= f.number_field :party_size %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

<h2>Reservations</h2>

<% @restaurant.reservations.each do |reservation| %>
	<p><%= reservation.reservation_time %> - <%= reservation.party_size %></p>
<% end %>